name: Build and Package es-map

on:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Enter DevShell
        uses: nicknovitski/nix-develop@v1

      #
      # - name: Enter flake dev environment
      #   run: nix develop .#default

      - name: Install pip for wheel downloads
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip

      - name: Export requirements.txt
        run: |
          uv export --format=requirements.txt -o requirements.txt
          grep -v "^-e " requirements.txt > tmp_requirements.txt

      - name: Create wheels directory
        run: mkdir -p wheels

      - name: Download wheels
        run: |
          pip download -r requirements.txt -d wheels \
          --platform windows \
          --only-binary=:all: \
          --no-deps

      - name: Zip wheels directory
        run: zip -r wheels.zip wheels

      - name: Upload wheels.zip artifact
        uses: actions/upload-artifact@v6
        with:
          name: wheels
          path: wheels.zip

      - name: Build es-map wheel
        run: uv build

      - name: Upload es-map wheel
        uses: actions/upload-artifact@v6
        with:
          name: es-map-wheel
          path: dist/*.whl
