name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          channels: conda-forge
          activate-environment: build-env

      - name: Install dependencies from pyproject.toml
        run: |
          choco install graphviz -y
          conda install pygraphviz graphviz
          python -m pip install --upgrade pip
          pip install build
          pip install .
          pip install nuitka

      - name: Test pygraphviz
        shell: pwsh
        run: |
          python -c "import pygraphviz; print('pygraphviz OK')"

      - name: Install Dependency Walker
        shell: pwsh
        run: |
          choco install depends -y

      - name: Build EXE
        run: |
          $extraFlags = ""
          if ($env:BUILD_TYPE -eq "release") {
              $extraFlags = "--onefile --lto=yes"
          }

          nuitka --standalone --lto=yes --follow-imports --output-dir=build --output-filename=es-map $extraFlags es_map/cli.py
      
      - name: Install EXE
        run: |
          mkdir -p out/bin
          Copy-Item -Path build/es-map.exe -Destination out/bin/es-map.exe

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: out/bin/es-map.exe

      - name: Test executable
        shell: pwsh
        run: |
          out/bin/es-map.exe
