name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          channels: conda-forge
          activate-environment: build-env

      - name: Install dependencies from pyproject.toml
        shell: bash -l {0}
        run: |
          choco install graphviz -y
          conda install pygraphviz graphviz
          python -m pip install --upgrade pip
          pip install build
          pip install .
          pip install nuitka

      - name: Test pygraphviz
        shell: pwsh
        run: |
          python -c "import pygraphviz; print('pygraphviz OK')"

      - name: Build EXE
        run: |
          $extraFlags = ""
          if ($env:BUILD_TYPE -eq "release") {
              $extraFlags = "--onefile --lto=yes"
          }

          nuitka --show-progress --assume-yes-for-downloads --standalone --lto=yes --output-dir=build --output-filename=es-map $extraFlags es_map/cli.py

      - name: Move executable
        shell: pwsh
        run: |
          mkdir -p out/bin
          $exe = "build\cli.dist\es-map.exe"
          Copy-Item -Path $exe -Destination out\bin\es-map.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: es-map-exe
          path: out/bin/es-map.exe

      - name: Func test exe
        shell: pwsh
        run: |
          & ".\out\bin\es-map.exe" --help
